feat: add article 503-504-errors-deepgram-api
deepgram/content pull request #22
Opened 2024-11-09 00:03 UTC by naomi-lgbt

2024-11-15 22:52 UTC, jpvajda requested changes
see comments for suggestions.

2024-11-15 22:52 UTC, jpvajda commented on articles/en/community/503-504-errors-deepgram-api-1304596979887640578.md
> +  JavaScript:
remove code.

2024-11-15 22:52 UTC, jpvajda commented on articles/en/community/503-504-errors-deepgram-api-1304596979887640578.md
> +- **Contact Support**: If issues persist, enterprise customers should reach out directly to Deepgram support for tailored troubleshooting and resolution.
An opportunity to use a default support statement here where we mention contacting a Deepgram representative or visiting our communities.

2024-11-17 22:04 UTC, naomi-lgbt commented on articles/en/community/503-504-errors-deepgram-api-1304596979887640578.md
> +- **Contact Support**: If issues persist, enterprise customers should reach out directly to Deepgram support for tailored troubleshooting and resolution.
https://app.asana.com/0/1207576726792593/1208782836187291/f

2024-11-22 02:39 UTC, merged