feat: add article utteranceend-endpointing-deepgram
deepgram/content pull request #26
Opened 2024-11-09 00:36 UTC by naomi-lgbt

2024-11-15 22:33 UTC, jpvajda requested changes
see comments for suggestions.

2024-11-15 22:33 UTC, jpvajda commented on articles/en/community/utteranceend-endpointing-deepgram-1304605237176176647.md
> +In a typical flow:
it might be hard, but having the LLM generate a flow diagram here could be useful.

2024-11-15 22:33 UTC, jpvajda commented on articles/en/community/utteranceend-endpointing-deepgram-1304605237176176647.md
> +#### References
Since we mention the SDKs here, linking to the SDKs would be useful.

2024-11-17 21:32 UTC, naomi-lgbt commented on articles/en/community/utteranceend-endpointing-deepgram-1304605237176176647.md
> +In a typical flow:
https://app.asana.com/0/1207576726792593/1208782836187279/f

2024-11-17 21:38 UTC, naomi-lgbt commented on articles/en/community/utteranceend-endpointing-deepgram-1304605237176176647.md
> +#### References
https://app.asana.com/0/1207576726792593/1208782836187283/f

2024-11-22 02:52 UTC, merged