feat: add article deepgram-speech-to-text-aws-lambda-websockets
deepgram/content pull request #28
Opened 2024-11-09 00:36 UTC by naomi-lgbt

2024-11-15 22:24 UTC, jpvajda requested changes
see comments for suggestions.

2024-11-15 22:24 UTC, jpvajda commented on articles/en/community/deepgram-speech-to-text-aws-lambda-websockets-1304605478935859208.md
> +### References
I'd expect to see some AWS references here.

2024-11-15 22:24 UTC, jpvajda commented on articles/en/community/deepgram-speech-to-text-aws-lambda-websockets-1304605478935859208.md
> +### Setup Deepgram SDK
Remove code sample.

2024-11-17 21:09 UTC, naomi-lgbt commented on articles/en/community/deepgram-speech-to-text-aws-lambda-websockets-1304605478935859208.md
> +### References
https://app.asana.com/0/1207576726792593/1208782836187274/f

2024-11-17 21:13 UTC, naomi-lgbt commented on articles/en/community/deepgram-speech-to-text-aws-lambda-websockets-1304605478935859208.md
> +### Setup Deepgram SDK
https://app.asana.com/0/1207576726792593/1208782836187274/f

2024-11-22 02:56 UTC, merged