feat: add article whisper-3-nova-3-deepgram-enhancements
deepgram/content pull request #34
Opened 2024-11-14 00:00 UTC by naomi-lgbt

2024-11-15 21:58 UTC, jpvajda requested changes
see comments for suggestions. I think we should close this PR and not publish it all given it's content about our roadmap plans.

2024-11-15 21:58 UTC, jpvajda commented on articles/en/community/whisper-3-nova-3-deepgram-enhancements-1306408209740730371.md
> +Feedback suggests that Whisper 3 provides superior transcription results under challenging conditions, such as noisy environments with overlapping speakers. This has prompted interest in integrating
I'm not sure if this is true.

2024-11-15 21:58 UTC, jpvajda commented on articles/en/community/whisper-3-nova-3-deepgram-enhancements-1306408209740730371.md
> +Our community has been curious about the potential inclusion of Whisper 3 in the Whisper Cloud services and the upcoming Nova-3 solutions. As of now, Deepgram has no immediate plans to integrate Whis
This feels like a piece of content we wouldn't post as it's speculating on our long term roadmap. I'd suggest we don't post threads like this which talk about when / if we might release things.

2024-11-17 20:50 UTC, naomi-lgbt commented on articles/en/community/whisper-3-nova-3-deepgram-enhancements-1306408209740730371.md
> +Our community has been curious about the potential inclusion of Whisper 3 in the Whisper Cloud services and the upcoming Nova-3 solutions. As of now, Deepgram has no immediate plans to integrate Whis
Ticketed https://app.asana.com/0/1207576726792593/1208782836187262/f

2024-11-17 20:50 UTC, closed without merging